fls
  : _0 -> _1 -> _1
  = <value> ;
tru
  : _0 -> _1 -> _0
  = <value> ;
if
  : (_0 -> _1 -> _2) -> _0 -> _1 -> _2
  = <value> ;
pair
  : _0 -> _1 -> (_0 -> _1 -> _2) -> _2
  = <value> ;
fst
  : ((_0 -> _1 -> _0) -> _2) -> _2
  = <value> ;
snd
  : ((_0 -> _1 -> _1) -> _2) -> _2
  = <value> ;
pair fls tru
  : ((_0 -> _1 -> _1) -> (_2 -> _3 -> _2) -> _4) -> _4
  = <value> ;
fst (pair fls tru)
  : _0 -> _1 -> _1
  = <value> ;
snd (pair fls tru)
  : _0 -> _0 -> _0
  = <value> ;
