Pair
  : * => * => * => *
  = \A :: * . \B :: * . \C :: * . (A -> B -> C) -> C ;
pair
  : 'A -> 'B -> ('A -> 'B -> 'C) -> 'C
  = \A :: * . \B :: * . \C :: * . \f : A . \s : B . \p : A -> B -> C . p f s ;
fst
  : (('A -> 'B -> 'A) -> 'C) -> 'C
  = \A :: * . \B :: * . \C :: * . \p : (A -> B -> A) -> C . p (\f : A . \s : B . f) ;
snd
  : (('A -> 'B -> 'B) -> 'C) -> 'C
  = \A :: * . \B :: * . \C :: * . \p : (A -> B -> B) -> C . p (\f : A . \s : B . s) ;
p
  : ((Bool 'A) -> (Bool 'A) -> 'B) -> 'B
  = \A :: * . \B :: * . \p : (A -> A -> A) -> (A -> A -> A) -> B . p (\t : A . \f : A . f) (\t : A . \f : A . t) ;
fst p
  : 'A -> 'A -> 'A
  = \A :: * . \t : A . \f : A . f ;
snd p
  : 'A -> 'A -> 'A
  = \A :: * . \t : A . \f : A . t ;
p
  : ((Nat 'A) -> (Nat 'A) -> 'B) -> 'B
  = \A :: * . \B :: * . \n1 : ((A -> A) -> A -> A) -> ((A -> A) -> A -> A) -> B . n1 (\s : A -> A . \z : A . z) (\s : A -> A . \z : A . s z) ;
fst p
  : ('A -> 'A) -> 'A -> 'A
  = \A :: * . \s : A -> A . \z : A . z ;
snd p
  : ('A -> 'A) -> 'A -> 'A
  = \A :: * . \s : A -> A . \z : A . s z ;
p
  : ((Bool 'A) -> (Nat 'B) -> 'C) -> 'C
  = \A :: * . \B :: * . \C :: * . \o1 : (A -> A -> A) -> ((B -> B) -> B -> B) -> C . o1 (\t : A . \f : A . f) (\s : B -> B . \z : B . z) ;
fst p
  : 'A -> 'A -> 'A
  = \A :: * . \t : A . \f : A . f ;
snd p
  : ('A -> 'A) -> 'A -> 'A
  = \A :: * . \s : A -> A . \z : A . z ;
