Pair
  : * => * => *
  = \A :: * . \B :: * . {fst : A; snd : B} ;
pair
  : forall A :: * . forall B :: * . A -> B -> {fst : A; snd : B}
  = \A :: * . \B :: * . \f : A . \s : B . {fst = f; snd = s} ;
fst
  : forall A :: * . forall B :: * . (Pair A B) -> A
  = \A :: * . \B :: * . \p : Pair A B . p.fst ;
snd
  : forall A :: * . forall B :: * . (Pair A B) -> B
  = \A :: * . \B :: * . \p : Pair A B . p.snd ;
p
  : {fst : Bool; snd : Bool}
  = {fst = [False {} of Bool]; snd = [True {} of Bool]} ;
fst Bool Bool p
  : Bool
  = [False {} of Bool] ;
snd Bool Bool p
  : Bool
  = [True {} of Bool] ;
p
  : {fst : Nat; snd : Nat}
  = {fst = [Zero {} of [Zero : {}; Succ : Nat]]; snd = [Succ [Zero {} of [Zero : {}; Succ : Nat]] of [Zero : {}; Succ : Nat]]} ;
fst Nat Nat p
  : Nat
  = [Zero {} of [Zero : {}; Succ : Nat]] ;
snd Nat Nat p
  : Nat
  = [Succ [Zero {} of [Zero : {}; Succ : Nat]] of [Zero : {}; Succ : Nat]] ;
p
  : {fst : Bool; snd : Nat}
  = {fst = [False {} of Bool]; snd = [Zero {} of [Zero : {}; Succ : Nat]]} ;
fst Bool Nat p
  : Bool
  = [False {} of Bool] ;
snd Bool Nat p
  : Nat
  = [Zero {} of [Zero : {}; Succ : Nat]] ;
