Pair
  : * => * => *
  = \A :: * . \B :: * . {fst : A; snd : B} ;
pair
  : forall A :: * . forall B :: * . A -> B -> {fst : A; snd : B}
  = \A :: * . \B :: * . \f : A . \s : B . {fst : f; snd : s} ;
fst
  : forall A :: * . forall B :: * . (Pair A B) -> A
  = \A :: * . \B :: * . \p : Pair A B . p.fst ;
snd
  : forall A :: * . forall B :: * . (Pair A B) -> B
  = \A :: * . \B :: * . \p : Pair A B . p.snd ;
p
  : {fst : forall A :: * . A -> A; snd : forall A :: * . A -> A -> A}
  = {fst : \A :: * . \x : A . x; snd : \A :: * . \x : A . \y : A . x} ;
fst forall A :: * . A -> A forall A :: * . A -> A -> A p
  : forall A :: * . A -> A
  = \A :: * . \x : A . x ;
snd forall A :: * . A -> A forall A :: * . A -> A -> A p
  : forall A :: * . A -> A -> A
  = \A :: * . \x : A . \y : A . x ;
