Pair
  : * => * => *
  = \A :: * . \B :: * . {fst : A; snd : B} ;
pair
  : forall A :: * . forall B :: * . A -> B -> {fst : A; snd : B}
  = \A :: * . \B :: * . \f : A . \s : B . {fst = f; snd = s} ;
fst
  : forall A :: * . forall B :: * . (Pair A B) -> A
  = \A :: * . \B :: * . \p : Pair A B . p.fst ;
snd
  : forall A :: * . forall B :: * . (Pair A B) -> B
  = \A :: * . \B :: * . \p : Pair A B . p.snd ;
p
  : {fst : [False : {}; True : {}]; snd : [False : {}; True : {}]}
  = {fst = [False {} of Bool]; snd = [True {} of Bool]} ;
fst Bool Bool p
  : [False : {}; True : {}]
  = [False {} of Bool] ;
snd Bool Bool p
  : [False : {}; True : {}]
  = [True {} of Bool] ;
p
  : {fst : [False : {}; True : {}]; snd : forall A :: * . A -> A}
  = {fst = [False {} of Bool]; snd = \A :: * . \x : A . x} ;
fst Bool forall A :: * . A -> A p
  : [False : {}; True : {}]
  = [False {} of Bool] ;
snd Bool forall A :: * . A -> A p
  : forall A :: * . A -> A
  = \A :: * . \x : A . x ;
