fls
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
tru
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
not
  : ((A -> B -> B) -> (C -> D -> C) -> E) -> E
  = \A . \B . \C . \D . \E . \p : (A -> B -> B) -> (C -> D -> C) -> E . p (\x : A . \y : B . y) (\x : C . \y : D . x) ;
and
  : (A -> (B -> C -> C) -> D) -> A -> D
  = \A . \B . \C . \D . \p : A -> (B -> C -> C) -> D . \q : A . p q (\x : B . \y : C . y) ;
or
  : ((A -> B -> A) -> C -> D) -> C -> D
  = \A . \B . \C . \D . \p : (A -> B -> A) -> C -> D . \q : C . p (\x : A . \y : B . x) q ;
if
  : (A -> B -> C) -> A -> B -> C
  = \A . \B . \C . \p : A -> B -> C . \x : A . \y : B . p x y ;
not fls
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
not tru
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
and fls fls
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
and fls tru
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
and tru fls
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
and tru tru
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
or fls fls
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
or fls tru
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
or tru fls
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
or tru tru
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
if fls fls tru
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
if tru fls tru
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
if fls (\x . x) (\y . y)
  : A -> A
  = \A . \y : A . y ;
pair fls tru
  : ((A -> B -> B) -> (C -> D -> C) -> E) -> E
  = \A . \B . \C . \D . \E . \p : (A -> B -> B) -> (C -> D -> C) -> E . p (\x : A . \y : B . y) (\x : C . \y : D . x) ;
fst (pair fls tru)
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
snd (pair fls tru)
  : A -> B -> A
  = \A . \B . \x : A . \y : B . x ;
pair fls (\x . x)
  : ((A -> B -> B) -> (C -> C) -> D) -> D
  = \A . \B . \C . \D . \p : (A -> B -> B) -> (C -> C) -> D . p (\x : A . \y : B . y) (\x : C . x) ;
fst (pair fls (\x . x))
  : A -> B -> B
  = \A . \B . \x : A . \y : B . y ;
snd (pair fls (\x . x))
  : A -> A
  = \A . \x : A . x ;
