id
  : A -> A
  = \F . \x : F . x ;
app
  : (A -> B) -> A -> B
  = \R . \Q . \x : R -> Q . \y : R . x y ;
id
  : A -> A
  = \V . \x : V . x ;
app
  : (A -> B) -> A -> B
  = \A1 . \B1 . \x : A1 -> B1 . \y : A1 . x y ;
let x = app in x
  : (A -> B) -> A -> B
  = \M1 . \N1 . \x : M1 -> N1 . \y : M1 . x y ;
let y = \z . z in y
  : A -> A
  = \X1 . \z : X1 . z ;
\x . let y = \z . z in y
  : A -> B -> B
  = \G2 . \L2 . \x : G2 . \z : L2 . z ;
\x . let y = \z . z in y x
  : A -> A
  = \Y2 . \x : Y2 . x ;
id id
  : A -> A
  = \J3 . \x : J3 . x ;
let x = app in let y = let z = x id in z in y
  : A -> A
  = \H4 . \y : H4 . y ;
\x . \y . let x = x y in \x . y x
  : ((A -> B) -> C) -> (A -> B) -> A -> B
  = \B5 . \A5 . \V4 . \x : (B5 -> A5) -> V4 . \y : B5 -> A5 . \C5 : B5 . y C5 ;
\x . let y = x in y
  : A -> A
  = \K5 . \x : K5 . x ;
\x . let y = \z . x in y
  : A -> B -> A
  = \X5 . \Y5 . \x : X5 . \z : Y5 . x ;
\x . let y = \z . x z in y
  : (A -> B) -> A -> B
  = \M6 . \L6 . \x : M6 -> L6 . \z : M6 . x z ;
\x . \y . let x = x y in x y
  : (A -> A -> B) -> A -> B
  = \C7 . \A7 . \x : C7 -> C7 -> A7 . \y : C7 . x y y ;
\x . let y = let z = x (\x . x) in z in y
  : ((A -> A) -> B) -> B
  = \S7 . \Q7 . \x : (S7 -> S7) -> Q7 . x (\x : S7 . x) ;
let id = \x . x in id id
  : A -> A
  = \G8 . \x : G8 . x ;
