pair
  : forall A . forall B . A -> B -> forall C . (A -> B -> C) -> C
  = \A . \B . \f : A . \s : B . \C . \p : A -> B -> C . p f s ;
fst
  : forall A . forall B . (forall C . (A -> B -> C) -> C) -> A
  = \A . \B . \p : forall C . (A -> B -> C) -> C . p A (\f : A . \s : B . f) ;
snd
  : forall A . forall B . (forall C . (A -> B -> C) -> C) -> B
  = \A . \B . \p : forall C . (A -> B -> C) -> C . p B (\f : A . \s : B . s) ;
p
  : forall C . ((forall A . A -> A -> A) -> (forall A . A -> A -> A) -> C) -> C
  = \C . \p : Bool -> Bool -> C . p (\A . \t : A . \f : A . f) (\A . \t : A . \f : A . t) ;
fst Bool Bool p
  : forall A . A -> A -> A
  = \A . \t : A . \f : A . f ;
snd Bool Bool p
  : forall A . A -> A -> A
  = \A . \t : A . \f : A . t ;
p
  : forall C . ((forall A . (A -> A) -> A -> A) -> (forall A . (A -> A) -> A -> A) -> C) -> C
  = \C . \p : Nat -> Nat -> C . p (\A . \s : A -> A . \z : A . z) (\A . \s : A -> A . \z : A . s z) ;
fst Nat Nat p
  : forall A . (A -> A) -> A -> A
  = \A . \s : A -> A . \z : A . z ;
snd Nat Nat p
  : forall A . (A -> A) -> A -> A
  = \A . \s : A -> A . \z : A . s z ;
p
  : forall C . ((forall A . A -> A -> A) -> (forall A . (A -> A) -> A -> A) -> C) -> C
  = \C . \p : Bool -> Nat -> C . p (\A . \t : A . \f : A . f) (\A . \s : A -> A . \z : A . z) ;
fst Bool Nat p
  : forall A . A -> A -> A
  = \A . \t : A . \f : A . f ;
snd Bool Nat p
  : forall A . (A -> A) -> A -> A
  = \A . \s : A -> A . \z : A . z ;
